id=moesif-gravitee-plugin
name=${project.name}
version=${project.version}
description=${project.description}
class=com.moesif.moesifgraviteeplugin.MoesifPolicy
type=policy
category=transformation
icon=moesif.svg
proxy=REQUEST,RESPONSE 
