= Moesif Policy

== Phase

[cols="^2,^2",options="header"]
|===
|onRequest|onResponse

|X
|X

|===

== Description

This policy logs API requests and responses to Moesif for API Analytics & Monetization.

**Required Configuration** 

- This policy requires you apply it to both the `onRequest` and `onResponse` phases for an API you want to monitor.
- You must also deploy the Moesif Resource to your APIM Gateway for the APIs you wish to monitor.

**Integration Guide**

For detailed install & configuration guidance:
 https://www.moesif.com/docs/server-integration/gravitee/

== Compatibility with APIM

|===
| Plugin version | APIM version

| Up to 1.x         | 4.0.x to latest
|===

== Configuration

This section describes the configuration options for the Moesif Policy.  The two header configs below read request headers to populate the optional event user ID and company ID in the Moesif event API: https://www.moesif.com/docs/api#log-an-api-call

|===
|Property |Required |Description |Type |Default

.^|userIdHeader
^.^| |The request header value to use for the event User ID, e.g. `X-User-Id` ^.^|string ^.^|-

.^|companyIdHeader
^.^| |The request header value to use for the Company ID, e.g. `X-Company-Id` ^.^|string ^.^|-

.^|debug
^.^| |Enable or disable debug logging. ^.^|boolean ^.^|false
|===